content:
  - name: posts
    label: Posts
    path: src/_posts
    type: collection
    fields:
      one
  - name: authors
    label: Authors
    path: src/_data/authors.json
    type: file
    fields:
      two
      three
  - name: pets
    label: pets
    path: src/_data/pets.json
    type: file
    fields:
      seven
      three